version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --lower_case_table_names=0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./php
    volumes:
      - ./app:/var/www/symfony_docker
      - ./legacy:/var/www/legacy
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  legacy-nginx:
      container_name: legacy-nginx
      image: nginx:stable-alpine
      ports:
        - '8081:80'
      volumes:
        - ./legacy:/var/www/legacy
        - ./nginx/legacy.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
        - database
volumes:
    mysql-data:
