#index:
#    path: /
#    controller: App\Controller\DefaultController::index
hello:
    path:     /
    controller: app.controller.user.show
    methods: GET

create:
    path: /create
    controller: app.controller.user.create
    methods: GET
